# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GIFUP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '5.6.1'
pod 'Kingfisher', '7.2.2'

  # Pods for GIFUP

  target 'GIFUPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GIFUPUITests' do
    # Pods for testing
  end

end
